Assignment 6

In [2]:
import pandas as pd

train_df = pd.read_csv("A06_train.csv", header=None)
test_df = pd.read_csv("A06_test.csv", header=None)

In [3]:
train_df

       0                                                  1
0      0  Billy Crystal attends the special 25th Anniver...
1      0  Ted Cruz pledges DOJ will open investigation o...
2      0  Howard U wins 2nd straight homecoming game wit...
3      0  How Medical Marijuana Could Combat the Opioid ...
4      0  Debating going to IHOP tomorrow morning or jus...
...   ..                                                ...
26494  0  The day Jonathan Cahn gave a prophetic sign to...
26495 -1  Hey @politico you need to drop that alt-right....
26496  1  Jose Mourinho: \""We want to win the playoff\u...
26497  0  Last night was #twEATup dinner at Bucci, tonig...
26498  1  #rtesoccer Robbie Keane saying he always knew ...

[26499 rows x 2 columns]

In [4]:
test_df

      0                                                  1
0     1  Club Pulse was fun af. Had a blast. Heading to...
1    -1  @MariahRoseFaith it won\u2019t work for me bec...
2    -1  From The Guardian: Benjamin Lee, 'Paul Haggis:...
3    -1  Arlington, TX students protest Trump https://t...
4    -1  @Anthglony 60 is too high, hed be asking for s...
...  ..                                                ...
6620  1  'man talk about TbT hey i gotta TGIF ... We go...
6621 -1  Photos may not come tonight. Updated to Window...
6622  0  @BLAKES_HT If i go to claytons tomorrow come o...
6623  1  My 1st live event Intercontinental Champion "R...
6624  1  I've always related so much to Ender and Valen...

[6625 rows x 2 columns]

In [5]:
#get the text
train_x = train_df[1]
#get the sentiment
train_y = train_df[0]

test_x = test_df[1]
test_y = test_df[0]

In [127]:
print('Train:', train_x.shape, train_y.shape)
print('Test :', test_x.shape, test_y.shape)

Train: (26499,) (26499,)
Test : (6625,) (6625,)

In [20]:
print(train_y[1234], train_x.iloc[1234].split())

-1 ['@dwiseXone', 'lmao', 'ha', 'bad', 'hombres!!!!!']

In [21]:
print(train_y[831], train_x.iloc[831].split())

0 ['The', 'Home', '&', 'Garden', 'Show', 'with', 'Ken', 'Brown,', 'Live', 'from', 'Menne', 'Nursery,', 'Sat', 'Sept', '22,', '11', 'am.', 'Listen', 'to', 'WBEN', 'am', '930', 'and', 'call', 'in', 'with', 'your', 'questions.']

In [22]:
print(train_y.value_counts(normalize=True))

0
 0    0.434356
 1    0.363070
-1    0.202574
Name: proportion, dtype: float64

Baseline

In [128]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()

train_x_counts = count_vect.fit_transform(train_x)
test_x_counts = count_vect.transform(test_x)

In [129]:
count_vect.vocabulary_

{'billy': 7371,
 'crystal': 12209,
 'attends': 5743,
 'the': 46209,
 'special': 43751,
 '25th': 836,
 'anniversary': 4900,
 'screening': 41601,
 'of': 34013,
 'u2019the': 48459,
 'princess': 37173,
 'bride': 8381,
 'u2019': 48347,
 'at': 5659,
 'new': 32755,
 'york': 52831,
 'festival': 17454,
 'http': 22302,
 'co': 10931,
 '5jufdobk': 1811,
 'ted': 45877,
 'cruz': 12200,
 'pledges': 36435,
 'doj': 14433,
 'will': 51312,
 'open': 34425,
 'investigation': 23779,
 'planned': 36352,
 'parenthood': 35301,
 'on': 34316,
 '1st': 630,
 'day': 12978,
 'in': 23229,
 'office': 34037,
 'xekfsuflxd': 52156,
 'howard': 22200,
 'wins': 51408,
 '2nd': 981,
 'straight': 44555,
 'homecoming': 21965,
 'game': 19001,
 'with': 51461,
 '21': 751,
 '20': 689,
 'victory': 49885,
 'over': 34837,
 'morgan': 31485,
 'state': 44235,
 'bison': 7435,
 'now': 33448,
 'meac': 30247,
 'how': 22199,
 'medical': 30297,
 'marijuana': 29670,
 'could': 11799,
 'combat': 11135,
 'opioid': 34458,
 'crisis': 12079,
 'https': 22303,
 'tonyfs8qxz': 47220,
 't979ajozw3': 45397,
 'debating': 13127,
 'going': 19848,
 'to': 47060,
 'ihop': 22960,
 'tomorrow': 47181,
 'morning': 31500,
 'or': 34529,
 'just': 25676,
 'sleeping': 43049,
 'kind': 26514,
 'confused': 11416,
 'why': 51226,
 'my': 32077,
 'amazon': 4539,
 'prime': 37159,
 'stuff': 44693,
 'that': 46187,
 'shipped': 42386,
 'today': 47075,
 'isn': 24016,
 'coming': 11171,
 'until': 49063,
 '19th': 487,
 '24th': 816,
 'certainly': 9889,
 'not': 33362,
 'two': 48140,
 'days': 12990,
 '77cajsfd': 2301,
 'u2019s': 48443,
 'al': 4168,
 'ien': 22859,
 'nascar': 32360,
 'person': 35847,
 'is': 23952,
 'friday': 18498,
 'hassler': 21103,
 'died': 13838,
 'crash': 11976,
 'daytona': 12994,
 '500': 1667,
 'qualifying': 38130,
 'race': 38368,
 '72': 2267,
 'lions': 28224,
 'taken': 45494,
 'back': 6175,
 'den': 13431,
 'for': 18161,
 'repairs': 39408,
 'if': 22867,
 'you': 52845,
 'follow': 18091,
 'pride': 37147,
 'bournemouth': 8086,
 'trail': 47464,
 'might': 30763,
 'be': 6721,
 'left': 27716,
 'scrat': 41591,
 'bit': 7438,
 'ly': 29052,
 'pq8pj6': 36898,
 'ric': 39847,
 'flair': 17827,
 'beloved': 6967,
 'legend': 27749,
 'john': 25233,
 'cena': 9848,
 'hated': 21116,
 'by': 8985,
 'pure': 37665,
 'wrestling': 51821,
 'fans': 17119,
 'even': 16518,
 'he': 21255,
 '16th': 379,
 'title': 46943,
 'they': 46583,
 'won': 51617,
 'equal': 16210,
 'ever': 16531,
 'summerslam': 44872,
 'woohoo': 51650,
 'am': 4505,
 'booked': 7957,
 'present': 37062,
 'ibm': 22711,
 'bluemix': 7724,
 'amp': 4656,
 'xpages': 52302,
 'dev': 13660,
 'team': 45784,
 'who': 51182,
 'are': 5276,
 'ready': 38813,
 'take': 45487,
 'their': 46364,
 'domino': 14475,
 'skills': 42913,
 'next': 32829,
 'level': 27898,
 'told': 47127,
 'mom': 31345,
 'wanted': 50587,
 'stay': 44265,
 'hotel': 22148,
 '18th': 411,
 'people': 35755,
 'but': 8886,
 'birthdays': 7425,
 'valentine': 49496,
 'lucky': 28907,
 'me': 30242,
 'curtis': 12388,
 'painter': 35140,
 'we': 50796,
 'have': 21139,
 'chance': 10007,
 'again': 3922,
 'can': 9285,
 'believe': 6939,
 'kerry': 26263,
 'collins': 11086,
 'didn': 13832,
 'throw': 46734,
 'us': 49229,
 'pick': 36102,
 'six': 42832,
 'tonight': 47209,
 'cold': 11037,
 'front': 18552,
 'metroplex': 30567,
 'happy': 20964,
 'tuvyo9kq': 48016,
 'eggbncype4': 15583,
 'oracle': 34534,
 'well': 50931,
 'august': 5805,
 '23rd': 796,
 '2015': 716,
 'inspiration': 23569,
 'bethechange': 7139,
 'beyourself': 7182,
 'health': 21290,
 '5tgrnei7be': 1876,
 'gublernation': 20461,
 'harper': 21039,
 'looks': 28615,
 'tired': 46932,
 'do': 14357,
 'sleep': 43043,
 'then': 46419,
 'should': 42489,
 'too': 47233,
 'get': 19373,
 'up': 49104,
 'early': 15266,
 'wants': 50590,
 'go': 19759,
 'see': 41784,
 'liza': 28348,
 'november': 33438,
 'kirby': 26567,
 'center': 9862,
 'it': 24073,
 'fucking': 18643,
 'minnelli': 30940,
 'jacob': 24414,
 'screamqueens': 41597,
 'wmhbeq1gxt': 51546,
 'thursday': 46768,
 'night': 32994,
 'helping': 21451,
 'recruiting': 39019,
 'stoops': 44502,
 'said': 41045,
 'think': 46616,
 'helps': 21452,
 'speaking': 43741,
 'kanye': 25917,
 'u002c': 48234,
 'genius': 19283,
 'like': 28100,
 'may': 30063,
 'make': 29396,
 'stupid': 44709,
 'choices': 10371,
 'sometimes': 43508,
 'his': 21742,
 'way': 50726,
 'thinking': 46621,
 'amazing': 4534,
 'wanna': 50582,
 'queen': 38161,
 'mary': 29840,
 'martinamcgowan': 29815,
 'good': 19900,
 'martina': 29813,
 'hope': 22064,
 'your': 52880,
 'great': 20194,
 'hot': 22142,
 'where': 51102,
 'steaming': 44289,
 'here': 21489,
 'bama': 6313,
 'played': 36389,
 'and': 4730,
 'perfected': 35786,
 'dragon': 14709,
 'dogma': 14420,
 'xbox': 52121,
 '360': 1171,
 'ps3': 37490,
 'come': 11141,
 'january': 24558,
 'll': 28379,
 'happen': 20954,
 'pc': 35573,
 'oldtraffordreds': 34222,
 'look': 28604,
 'past': 35410,
 'record': 38995,
 'awful': 5985,
 'nearly': 32583,
 'got': 20000,
 'barca': 6413,
 'relegated': 39286,
 'finished': 17670,
 '5th': 1877,
 'wif': 51264,
 'bayern': 6577,
 'b4': 6099,
 'sacked': 40979,
 'tuesday': 47926,
 'playing': 36400,
 'st': 44098,
 'albans': 4209,
 'cheeky': 10172,
 'little': 28285,
 'venue': 49721,
 'called': 9206,
 'horn': 22096,
 're': 38788,
 'local': 28487,
 'out': 34749,
 'support': 44988,
 'noise': 33231,
 'supersonic': 44967,
 'paul': 35490,
 'foot': 18128,
 'boris': 8015,
 'december': 13162,
 'runrig': 40717,
 'boring': 8014,
 'car': 9412,
 'turbonegro': 47969,
 'pretty': 37112,
 'broke': 8491,
 'christmas': 10453,
 'yay': 52552,
 'tony': 47215,
 'romo': 40369,
 'other': 34687,
 'than': 46156,
 'dallas': 12672,
 'wouldn': 51751,
 'receive': 38949,
 'anywhere': 5034,
 'near': 32580,
 'same': 41124,
 'media': 30288,
 'slurpage': 43109,
 'dda6fly3qj': 13053,
 'its': 24116,
 'always': 4487,
 'valentines': 49498,
 'this': 46637,
 'one': 34324,
 'babyselcaday': 6165,
 'fi9wyn1tbz': 17537,
 'really': 38867,
 'chelsea': 10194,
 'start': 44209,
 'baba': 6142,
 'instead': 23598,
 'ivanovic': 24199,
 'saturday': 41308,
 'literally': 28272,
 'aged': 3936,
 'about': 3400,
 'years': 52612,
 'summer': 44867,
 'originalfunko': 34604,
 'definitely': 13280,
 'teen': 45896,
 'wolf': 51594,
 'hart': 21069,
 'dixie': 14217,
 'light': 28080,
 'characters': 10056,
 '8lvlpqekkp': 2780,
 'black': 7514,
 'sonoma': 43539,
 'door': 14557,
 'armoire': 5348,
 'nationalfastfoodday': 32419,
 'exkoi9wrpt': 16689,
 'would': 51748,
 'poetic': 36564,
 'nintendo': 33054,
 'became': 6811,
 'sony': 43544,
 'party': 35375,
 'developer': 13672,
 'also': 4452,
 'choosing': 10385,
 'consoles': 11499,
 'every': 16541,
 'generation': 19268,
 'very': 49774,
 'easy': 15310,
 'know': 26744,
 'when': 51094,
 'bed': 6842,
 'pocket': 36545,
 'gilmore': 19534,
 'girls': 19577,
 'off': 34020,
 'carrow': 9526,
 'road': 40149,
 'mighty': 30764,
 'canaries': 9295,
 'shit': 42398,
 'all': 4333,
 'stoke': 44476,
 'angry': 4831,
 'bloke': 7681,
 'no': 33167,
 'doubt': 14601,
 'sat': 41291,
 'behind': 6902,
 'donald': 14483,
 'trump_': 47756,
 'melania': 30380,
 'mad': 29234,
 'after': 3901,
 'joke': 25307,
 'michelle': 30691,
 'obama': 33837,
 'speech': 43781,
 'video': 49890,
 'chf': 10261,
 'usd': 49254,
 'exchange': 16629,
 'rate': 38647,
 'trump': 47749,
 'prompted': 37353,
 'round': 40481,
 'looking': 28610,
 'forward': 18256,
 'attending': 5742,
 'event': 16525,
 'reframing': 39140,
 'conversation': 11608,
 'abortion': 3390,
 'join': 25298,
 'kziftiadug': 27120,
 'prisonplanet': 37197,
 'expose': 16774,
 'illegal': 23041,
 'dead': 13079,
 'votes': 50207,
 'dems': 13428,
 'potentially': 36817,
 'create': 12009,
 'bigger': 7304,
 'djt': 14263,
 'rawbcas3': 38694,
 'alright': 4443,
 'let': 27862,
 'want': 50585,
 'ac': 3445,
 'dc': 13018,
 'wednesday': 50856,
 'metlife': 30560,
 'meet': 30328,
 'secaucus': 41748,
 'station': 44251,
 'drive': 14816,
 'jerrietrash': 24847,
 'libby': 27999,
 'stillwithher': 44436,
 'hi': 21608,
 'congrats': 11424,
 'picked': 36104,
 'our': 34741,
 'site': 42814,
 'description': 13565,
 'gargriff': 19068,
 'nkeylock': 33109,
 'yes': 52652,
 'ga': 18901,
 'drill': 14801,
 'use': 49257,
 'band': 6329,
 'saw': 41355,
 'measure': 30272,
 'cracking': 11949,
 'castle': 9596,
 'shaped': 42188,
 'birdhouse': 7415,
 'tid': 46797,
 'info': 23428,
 'beitthemeans': 6920,
 'nov': 33427,
 '23': 787,
 'capt': 9400,
 'stabb': 44103,
 'tuggo': 47930,
 'evdqosrw': 16512,
 'doing': 14429,
 'any': 5017,
 'batman': 6542,
 'impersonations': 23166,
 'time': 46851,
 'type': 48190,
 'mon': 31357,
 'please': 36427,
 'imagine': 23093,
 'arnett': 5360,
 'gob': 19782,
 'bluth': 7747,
 'shouting': 42500,
 'andre': 4750,
 'johnson': 25288,
 'did': 13831,
 'practice': 36922,
 'texans': 46083,
 'arian': 5305,
 'foster': 18263,
 'limited': 28153,
 'brian': 8351,
 'cushing': 12399,
 'expected': 16709,
 'play': 36382,
 'put': 37704,
 'song': 43522,
 'from': 18546,
 'thrones': 46730,
 'soundtrack': 43633,
 'playlist': 36402,
 'yoga': 52804,
 'class': 10694,
 'teaching': 45779,
 'protecting': 37412,
 'brand': 8219,
 'more': 31477,
 'trade': 47441,
 'mark': 29703,
 'red': 39028,
 'bull': 8750,
 'etrhxeyiem': 16435,
 'top': 47256,
 '10': 190,
 'search': 41713,
 'engine': 16040,
 'referrals': 39122,
 'tve': 48035,
 'mike': 30787,
 'molly': 31339,
 'related': 39260,
 'thanks': 46165,
 'melissa': 30393,
 'mccarthy': 30125,
 'win': 51362,
 'emmys': 15927,
 'ok': 34172,
 'check': 10158,
 'tennis': 45991,
 'isner': 24017,
 'federer': 17364,
 'heading': 21270,
 'into': 23734,
 'tiebreak': 46803,
 'watched': 50671,
 'joyful': 25443,
 '30th': 1106,
 'keeps': 26138,
 'getting': 19402,
 'better': 7164,
 'actor': 3593,
 'artists': 5447,
 'kekepalmer': 26161,
 'mecrazymatt': 30282,
 'fa': 16940,
 'cup': 12349,
 'sf': 42065,
 'carling': 9466,
 'final': 17628,
 'lost': 28683,
 'pens': 35743,
 'been': 6859,
 'true': 47728,
 'leader': 27629,
 'took': 47239,
 'places': 36329,
 'ain': 4056,
 'u2019t': 48458,
 'starrhaus': 44205,
 'beachpeanuts': 6735,
 'washingtonpost': 50651,
 'bad': 6209,
 'admin': 3706,
 'yesterday': 52663,
 'qgflpxrewz': 37940,
 'hatepash1': 21119,
 'daario': 12597,
 'charming': 10099,
 'original': 34603,
 '4zpoq6zdfa': 1662,
 'foxandfriends': 18298,
 'hillary': 21691,
 'sorry': 43595,
 'she': 42267,
 'facing': 16978,
 'criminal': 12065,
 'charges': 10066,
 'what': 51057,
 'found': 18275,
 'her': 21479,
 'email': 15857,
 'sport': 43898,
 'ct200h': 12247,
 'lexus': 27929,
 'eats': 15322,
 'asphalt': 5563,
 'sips': 42777,
 'fuel': 18663,
 'wngt4byhoj': 51560,
 'holger': 21910,
 'another': 4937,
 'selection': 41832,
 'headache': 21260,
 'carl': 9457,
 'valeri': 49500,
 'possible': 36789,
 'injury': 23484,
 '30': 1083,
 'mins': 30954,
 'cesena': 9903,
 'as': 5468,
 'indy': 23384,
 'once': 34320,
 'alt': 4453,
 'rightists': 39947,
 'hate': 21113,
 'these': 46519,
 'guys': 20560,
 'perfect': 35782,
 'jeeze': 24752,
 '13ymtftatt': 314,
 'boys': 8136,
 'care': 9434,
 'business': 8869,
 '17': 382,
 'damn': 12700,
 'viqueens': 49988,
 'felix': 17403,
 'dez': 13711,
 'went': 50960,
 'ham': 20853,
 'topless': 47265,
 'protestors': 37428,
 'march': 29616,
 'venice': 49703,
 'beach': 6728,
 'kick': 26422,
 'gender': 19255,
 'inequality': 23392,
 'lzupp4zb2u': 29114,
 'lobodude03': 28481,
 'lair': 27283,
 'tailgate': 45469,
 'msmarbella': 31794,
 'statistar30': 44254,
 'need': 32603,
 'voter': 50204,
 'suppression': 45002,
 'documentation': 14396,
 'zrk8fqxgxe': 53464,
 '3fab5all': 1239,
 'hiberlinberlin': 21618,
 'tomgrantpi': 47166,
 'knew': 26705,
 'april': 5194,
 '1994': 480,
 'kurt': 27002,
 'cobain': 10963,
 'was': 50643,
 'die': 13837,
 'must': 31999,
 'known': 26748,
 'emotional': 15938,
 'reasons': 38906,
 'emmettrensin': 15923,
 'sure': 45020,
 'some': 43490,
 'liberals': 28009,
 'exploited': 16753,
 'assail': 5575,
 'whole': 51192,
 'obscures': 33883,
 'much': 31856,
 'judgejeanine': 25570,
 'realdonaldtrump': 38841,
 'mike_pence': 30790,
 'speakerryan': 43736,
 'isis': 23991,
 'films': 17620,
 'men': 30437,
 'laughing': 27475,
 'while': 51122,
 'woman': 51606,
 'raped': 38610,
 'background': 6188,
 'ascuidnxyd': 5482,
 'ryan': 40827,
 'reynolds': 39755,
 'action': 3579,
 'role': 40314,
 'green': 20212,
 'lantern': 27376,
 'shows': 42527,
 'safe': 41022,
 'house': 22175,
 'isnt': 24018,
 'used': 49259,
 'barely': 6427,
 'watching': 50675,
 'dexter': 13709,
 'evening': 16519,
 'love': 28735,
 'show': 42509,
 'twaimz': 48056,
 'vines': 49957,
 'himself': 21716,
 'dropping': 14856,
 'ass': 5572,
 'ahs': 4017,
 'freakshow': 18414,
 'im': 23076,
 'content': 11550,
 'white': 51147,
 'boy': 8122,
 'nicki': 32931,
 'minaj': 30896,
 'best': 7108,
 'female': 17415,
 'rapper': 38621,
 'beg': 6879,
 'differ': 13852,
 'since': 42732,
 'schizophrenics': 41468,
 'recognized': 38983,
 'tomfgoodwin': 47163,
 'morganhousel': 31489,
 'id': 22775,
 'print': 37182,
 'registration': 39186,
 'concert': 11349,
 'promoters': 37346,
 'c3': 9055,
 'presents': 37070,
 'sold': 43446,
 'last': 27421,
 'truly': 47745,
 'austin': 5836,
 'city': 10595,
 'limits': 28156,
 'i2qgi0mnij': 22580,
 'trillllaa_': 47645,
 'mobile': 31247,
 'so': 43347,
 'switch': 45234,
 'cmbsweden': 10882,
 'responsibility': 39597,
 'key': 26315,
 'michael': 30658,
 'moore': 31457,
 've': 49650,
 'jamesron1980': 24507,
 'wish': 51446,
 'putin': 37709,
 'hague': 20757,
 'russians': 40761,
 'deserve': 13573,
 'him': 21712,
 'ukropo4ka': 48713,
 'geenpeil': 19233,
 'stacejarman': 44109,
 'brendanabc2': 8319,
 'toysrus': 47382,
 'yikes': 52714,
 'idea': 22783,
 'don': 14479,
 'kids': 26449,
 'right': 39940,
 'age': 3934,
 'range': 38585,
 'hatchimals': 21110,
 'embracing': 15880,
 'oversized': 34875,
 'sun': 44884,
 'glass': 19643,
 'glasses': 19644,
 'awesome': 5981,
 'feel': 17382,
 'jackie': 24386,
 'struggle': 44662,
 'grind': 20303,
 'came': 9250,
 'heavy': 21355,
 'high': 21647,
 'god': 19796,
 'does': 14409,
 'bachelor': 6173,
 'degree': 13298,
 'mine': 30910,
 'okay': 34177,
 'fidel': 17555,
 'down': 14631,
 'santos': 41237,
 'maduro': 29284,
 'rt': 40593,
 'foodprincess': 18112,
 'wonderful': 51620,
 'company': 11252,
 'gr8': 20076,
 'food': 18108,
 'chinatown': 10337,
 'tour': 47345,
 'guide': 20478,
 'ziggysmogdust': 53319,
 'jaypfrancis': 24641,
 'irene': 23907,
 'shaker': 42136,
 'post': 36792,
 'pone': 36674,
 'halloween': 20836,
 'tf': 46097,
 'wensday': 50959,
 'candy': 9318,
 'sunday': 44891,
 'gonna': 19889,
 'movie': 31644,
 'marathon': 29603,
 'friend': 18508,
 'twilight': 48102,
 'moon': 31447,
 'eclipse': 15387,
 'bd1': 6691,
 'runaways': 40702,
 'adventureland': 3765,
 'russian_starr': 40759,
 'listen': 28255,
 'npr': 33480,
 'interview': 23718,
 'saakashvili': 40955,
 'thoughts': 46694,
 'analysis': 4709,
 'rdf6uvjwbo': 38779,
 't_yeon9': 45409,
 'eonni': 16147,
 'mama': 29471,
 'award': 5968,
 'ost': 34665,
 'fighting': 17582,
 'jan': 24533,
 '19': 413,
 'an': 4692,
 'ordinary': 34565,
 'fan': 17094,
 'somewhere': 43512,
 'papaesoco': 35251,
 'catlover1943': 9650,
 'alternet': 4463,
 'coal': 10950,
 'mining': 30927,
 'peabody': 35623,
 'etc': 16402,
 'invent': 23765,
 'robots': 40220,
 'before': 6877,
 'hire': 21734,
 'workers': 51689,
 'frankthorp': 18391,
 'repkevincramer': 39434,
 'tribe': 47619,
 'has': 21083,
 'legal': 27734,
 'standing': 44164,
 'treaty': 47577,
 '1851': 401,
 'army': 5354,
 'corps': 11726,
 'working': 51694,
 'fossil': 18261,
 'fuels': 18666,
 'pack': 35084,
 'brown': 8544,
 'rebound': 38930,
 'lorenzo': 28663,
 'wolfpack': 51599,
 'hoping': 22080,
 'against': 3923,
 'fwleb5f3': 18803,
 'raleighnews': 38524,
 'cameron': 9257,
 'telegraph': 45931,
 'refugeecrisis': 39148,
 'supports': 44994,
 'tory': 47303,
 'drowned': 14864,
 'children': 10315,
 'beaches': 6733,
 'live': 28305,
 'radio': 38418,
 '00': 0,
 'est': 16361,
 'tune': 47948,
 'bbeilrlhw5': 6634,
 'thatfridayfeeling': 46195,
 'thought': 46692,
 'queue': 38183,
 'digi': 13870,
 'making': 29413,
 'upset': 49158,
 'caught': 9665,
 'ufo': 48620,
 'engaging': 16038,
 'warp': 50628,
 'photo': 36044,
 'asy4doye': 5654,
 'psychosix': 37542,
 'smoker': 43208,
 'beohner': 7049,
 '98': 2909,
 'fact': 16980,
 'dow': 14628,
 '634': 1996,
 'boehner': 7856,
 'owns': 34936,
 'point': 36573,
 'p2': 34994,
 'fok': 18077,
 'maddow': 29249,
 'teaparty': 45829,
 '_four_horsemen': 3132,
 'independent': 23313,
 'death': 13115,
 'penalty': 35717,
 'imaginary': 23090,
 'crimes': 12064,
 'simply': 42716,
 'barbaric': 6403,
 'mrssole': 31746,
 'lol': 28541,
 'oh': 34098,
 'free': 18429,
 'invite': 23794,
 'women': 51609,
 'church': 10505,
 'weekend': 50872,
 'miss': 31015,
 'largest': 27392,
 'book': 7956,
 'happening': 20956,
 'capitol': 9391,
 'onedirection': 34326,
 'directioner': 13967,
 'uzxs7pxykl': 49420,
 'turns': 48001,
 'match': 29915,
 'lane': 27357,
 'ramires': 38551,
 '100th': 198,
 'club': 10855,
 'big': 7287,
 'milestone': 30844,
 'guest': 20472,
 'super': 44934,
 'kris': 26872,
 'gordon': 19974,
 'rocked': 40242,
 'wisconsin': 51435,
 'athletic': 5678,
 'armqovhe': 5351,
 'maarvi': 29188,
 'having': 21149,
 'zac': 53154,
 'efron': 15571,
 'vs': 50271,
 'ashley': 5504,
 'tisdale': 46937,
 'suite': 44842,
 'life': 28056,
 'moment': 31348,
 'minus': 30958,
 'kiss': 26584,
 'powerpoint': 36861,
 'vegetarianism': 49671,
 'unhealthy': 48921,
 'double': 14592,
 'shot': 42481,
 'ticket': 46791,
 'power': 36851,
 '106': 215,
 'hear': 21302,
 'chris': 10403,
 'songs': 43526,
 'caller': 9208,
 '888': 2705,
 '1067': 216,
 'wtf': 51888,
 'act': 3572,
 '2wayqall': 1048,
 'liespeoplealwaystell': 28053,
 'pole': 36605,
 'national': 32416,
 'margarita': 29642,
 'ash': 5491,
 'mdhibbert': 30233,
 'there': 46473,
 'volvo': 50179,
 'hib': 21617,
 'plate': 36371,
 'spotted': 43925,
 ...}

In [130]:
train_x_counts.shape

(26499, 53586)

In [131]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
#max_iter = 1000 suggestion by claude
lr = LogisticRegression(max_iter=1000)
lr.fit(train_x_counts, train_y)
acc = accuracy_score(test_y, lr.predict(test_x_counts))
print(round(acc, 4))

0.6571

Enhanced system: stopwords

In [132]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [133]:
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

filtered_train = []

for text in train_x:
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
    filtered_train.append(" ".join(filtered_tokens))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [134]:
filtered_test = []

for text in test_x:
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
    filtered_test.append(" ".join(filtered_tokens))

In [135]:
print(len(train_x.iloc[0].split()))
print(len(filtered_train[0].split()))

18
16

In [136]:
print(train_x.iloc[0].split())
print(filtered_train[0].split())

['Billy', 'Crystal', 'attends', 'the', 'special', '25th', 'Anniversary', 'Screening', 'of', '\\u2019The', 'Princess', 'Bride\\u2019', 'at', 'the', 'New', 'York', 'Festival', 'http://t.co/5juFdoBK']
['Billy', 'Crystal', 'attends', 'special', '25th', 'Anniversary', 'Screening', '\\u2019The', 'Princess', 'Bride\\u2019', 'New', 'York', 'Festival', 'http', ':', '//t.co/5juFdoBK']

In [137]:
train_x_counts = count_vect.fit_transform(filtered_train)
test_x_counts = count_vect.transform(filtered_test)

In [138]:
count_vect.vocabulary_

{'billy': 7365,
 'crystal': 12201,
 'attends': 5741,
 'special': 43729,
 '25th': 836,
 'anniversary': 4898,
 'screening': 41580,
 'u2019the': 48432,
 'princess': 37152,
 'bride': 8374,
 'u2019': 48320,
 'new': 32737,
 'york': 52802,
 'festival': 17445,
 'http': 22287,
 'co': 10923,
 '5jufdobk': 1811,
 'ted': 45855,
 'cruz': 12192,
 'pledges': 36414,
 'doj': 14425,
 'open': 34407,
 'investigation': 23763,
 'planned': 36331,
 'parenthood': 35280,
 '1st': 630,
 'day': 12970,
 'office': 34019,
 'xekfsuflxd': 52127,
 'howard': 22185,
 'wins': 51379,
 '2nd': 981,
 'straight': 44533,
 'homecoming': 21950,
 'game': 18991,
 '21': 751,
 '20': 689,
 'victory': 49858,
 'morgan': 31468,
 'state': 44213,
 'bison': 7429,
 'meac': 30230,
 'medical': 30280,
 'marijuana': 29653,
 'could': 11791,
 'combat': 11127,
 'opioid': 34440,
 'crisis': 12071,
 'https': 22288,
 'tonyfs8qxz': 47194,
 't979ajozw3': 45375,
 'debating': 13119,
 'going': 19838,
 'ihop': 22945,
 'tomorrow': 47155,
 'morning': 31483,
 'sleeping': 43027,
 'kind': 26497,
 'confused': 11408,
 'amazon': 4537,
 'prime': 37138,
 'stuff': 44671,
 'shipped': 42364,
 'today': 47049,
 'coming': 11163,
 '19th': 487,
 '24th': 816,
 'certainly': 9881,
 'two': 48113,
 'days': 12982,
 '77cajsfd': 2301,
 'u2019s': 48416,
 'al': 4166,
 'ien': 22844,
 'nascar': 32342,
 'person': 35826,
 'friday': 18488,
 'hassler': 21091,
 'died': 13830,
 'crash': 11968,
 'daytona': 12986,
 '500': 1667,
 'qualifying': 38109,
 'race': 38347,
 '72': 2267,
 'lions': 28207,
 'taken': 45472,
 'back': 6173,
 'den': 13423,
 'repairs': 39387,
 'follow': 18081,
 'pride': 37126,
 'bournemouth': 8079,
 'trail': 47438,
 'might': 30746,
 'left': 27699,
 'scrat': 41570,
 'bit': 7432,
 'ly': 29035,
 'pq8pj6': 36877,
 'ric': 39826,
 'flair': 17817,
 'beloved': 6963,
 'legend': 27732,
 'john': 25216,
 'cena': 9840,
 'hated': 21104,
 'pure': 37644,
 'wrestling': 51792,
 'fans': 17110,
 'even': 16509,
 '16th': 379,
 'title': 46917,
 'they': 46559,
 'wo': 51545,
 'equal': 16201,
 'ever': 16522,
 'summerslam': 44850,
 'woohoo': 51621,
 'booked': 7951,
 'present': 37041,
 'ibm': 22696,
 'bluemix': 7718,
 'amp': 4654,
 'xpages': 52273,
 'dev': 13652,
 'team': 45762,
 'ready': 38792,
 'take': 45465,
 'domino': 14467,
 'skills': 42891,
 'next': 32811,
 'level': 27881,
 'told': 47101,
 'mom': 31328,
 'wanted': 50560,
 'stay': 44243,
 'hotel': 22133,
 '18th': 411,
 'people': 35734,
 'birthdays': 7419,
 'valentine': 49469,
 'lucky': 28890,
 'curtis': 12380,
 'painter': 35119,
 'chance': 9999,
 'ca': 9094,
 'believe': 6935,
 'kerry': 26246,
 'collins': 11078,
 'throw': 46708,
 'us': 49202,
 'pick': 36081,
 'six': 42810,
 'tonight': 47183,
 'cold': 11029,
 'front': 18542,
 'metroplex': 30550,
 'happy': 20952,
 'tuvyo9kq': 47990,
 'eggbncype4': 15574,
 'oracle': 34516,
 'well': 50904,
 'august': 5803,
 '23rd': 796,
 '2015': 716,
 'inspiration': 23554,
 'bethechange': 7134,
 'beyourself': 7176,
 'health': 21277,
 '5tgrnei7be': 1876,
 'gublernation': 20449,
 'harper': 21027,
 'looks': 28598,
 'tired': 46906,
 'sleep': 43021,
 'get': 19363,
 'early': 15257,
 'wants': 50563,
 'go': 19749,
 'see': 41763,
 'liza': 28331,
 'november': 33420,
 'kirby': 26550,
 'center': 9854,
 'fucking': 18633,
 'minnelli': 30923,
 'jacob': 24397,
 'screamqueens': 41576,
 'wmhbeq1gxt': 51517,
 'thursday': 46742,
 'night': 32976,
 'helping': 21438,
 'recruiting': 38998,
 'stoops': 44480,
 'said': 41024,
 'think': 46592,
 'helps': 21439,
 'speaking': 43719,
 'kanye': 25900,
 'u002c': 48207,
 'he': 21242,
 'genius': 19273,
 'like': 28083,
 'may': 30046,
 'make': 29379,
 'stupid': 44687,
 'choices': 10363,
 'sometimes': 43486,
 'way': 50699,
 'thinking': 46597,
 'amazing': 4532,
 'wan': 50540,
 'na': 32220,
 'queen': 38140,
 'mary': 29823,
 'martinamcgowan': 29798,
 'good': 19889,
 'martina': 29796,
 'hope': 22049,
 'great': 20182,
 'hot': 22127,
 'steaming': 44267,
 'bama': 6311,
 'played': 36368,
 'perfected': 35765,
 'dragon': 14701,
 'dogma': 14412,
 'xbox': 52092,
 '360': 1171,
 'ps3': 37469,
 'come': 11133,
 'january': 24541,
 'll': 28362,
 'happen': 20942,
 'pc': 35552,
 'oldtraffordreds': 34204,
 'look': 28587,
 'past': 35389,
 'record': 38974,
 'awful': 5983,
 'nearly': 32565,
 'got': 19989,
 'barca': 6411,
 'relegated': 39265,
 'finished': 17660,
 '5th': 1877,
 'wif': 51235,
 'bayern': 6575,
 'b4': 6097,
 'sacked': 40958,
 'tuesday': 47900,
 'playing': 36379,
 'st': 44076,
 'albans': 4207,
 'cheeky': 10164,
 'little': 28268,
 'venue': 49694,
 'called': 9199,
 'horn': 22081,
 're': 38767,
 'local': 28470,
 'support': 44966,
 'noise': 33213,
 'supersonic': 44945,
 'paul': 35469,
 'foot': 18118,
 'boris': 8009,
 'december': 13154,
 'runrig': 40696,
 'boring': 8008,
 'car': 9404,
 'turbonegro': 47943,
 'pretty': 37091,
 'broke': 8484,
 'christmas': 10445,
 'yay': 52523,
 'tony': 47189,
 'romo': 40348,
 'dallas': 12664,
 'would': 51719,
 'receive': 38928,
 'anywhere': 5032,
 'near': 32562,
 'media': 30271,
 'slurpage': 43087,
 'dda6fly3qj': 13045,
 'always': 4485,
 'valentines': 49471,
 'one': 34306,
 'babyselcaday': 6163,
 'fi9wyn1tbz': 17527,
 'really': 38846,
 'chelsea': 10186,
 'start': 44187,
 'baba': 6140,
 'instead': 23583,
 'ivanovic': 24182,
 'saturday': 41287,
 'literally': 28255,
 'aged': 3934,
 'years': 52583,
 'summer': 44845,
 'originalfunko': 34586,
 'definitely': 13272,
 'teen': 45874,
 'wolf': 51565,
 'hart': 21057,
 'dixie': 14209,
 'light': 28063,
 'characters': 10048,
 '8lvlpqekkp': 2780,
 'black': 7508,
 'sonoma': 43517,
 'door': 14549,
 'armoire': 5346,
 'nationalfastfoodday': 32401,
 'exkoi9wrpt': 16680,
 'poetic': 36543,
 'nintendo': 33036,
 'became': 6809,
 'sony': 43522,
 'party': 35354,
 'developer': 13664,
 'also': 4450,
 'choosing': 10377,
 'consoles': 11491,
 'every': 16532,
 'generation': 19258,
 'easy': 15301,
 'know': 26727,
 'bed': 6839,
 'pocket': 36524,
 'gilmore': 19524,
 'girls': 19567,
 'carrow': 9518,
 'road': 40128,
 'mighty': 30747,
 'canaries': 9288,
 'shit': 42376,
 'stoke': 44454,
 'angry': 4829,
 'bloke': 7675,
 'doubt': 14593,
 'sat': 41270,
 'behind': 6898,
 'donald': 14475,
 'trump_': 47730,
 'melania': 30363,
 'mad': 29217,
 'joke': 25290,
 'michelle': 30674,
 'obama': 33819,
 'speech': 43759,
 'video': 49863,
 'chf': 10253,
 'usd': 49227,
 'exchange': 16620,
 'rate': 38626,
 'trump': 47723,
 'prompted': 37332,
 'round': 40460,
 'looking': 28593,
 'forward': 18246,
 'attending': 5740,
 'event': 16516,
 'reframing': 39119,
 'conversation': 11600,
 'abortion': 3390,
 'join': 25281,
 'kziftiadug': 27103,
 'prisonplanet': 37176,
 'expose': 16765,
 'illegal': 23026,
 'dead': 13071,
 'votes': 50180,
 'dems': 13420,
 'potentially': 36796,
 'create': 12001,
 'bigger': 7298,
 'djt': 14255,
 'rawbcas3': 38673,
 'alright': 4441,
 'let': 27845,
 'want': 50558,
 'ac': 3444,
 'dc': 13010,
 'wednesday': 50829,
 'metlife': 30543,
 'meet': 30311,
 'secaucus': 41727,
 'station': 44229,
 'drive': 14808,
 'jerrietrash': 24830,
 'libby': 27982,
 'stillwithher': 44414,
 'hi': 21593,
 'congrats': 11416,
 'picked': 36083,
 'site': 42792,
 'description': 13557,
 'gargriff': 19058,
 'nkeylock': 33091,
 'yes': 52623,
 'ga': 18891,
 'drill': 14793,
 'use': 49230,
 'band': 6327,
 'saw': 41334,
 'measure': 30255,
 'cracking': 11941,
 'castle': 9588,
 'shaped': 42166,
 'birdhouse': 7409,
 'tid': 46771,
 'info': 23413,
 'beitthemeans': 6916,
 'nov': 33409,
 '23': 787,
 'capt': 9392,
 'stabb': 44081,
 'tuggo': 47904,
 'evdqosrw': 16503,
 'batman': 6540,
 'impersonations': 23151,
 'time': 46825,
 'type': 48163,
 'mon': 31340,
 'please': 36406,
 'imagine': 23078,
 'arnett': 5358,
 'gob': 19772,
 'bluth': 7741,
 'shouting': 42478,
 'andre': 4748,
 'johnson': 25271,
 'practice': 36901,
 'texans': 46061,
 'arian': 5303,
 'foster': 18253,
 'limited': 28136,
 'brian': 8344,
 'cushing': 12391,
 'expected': 16700,
 'play': 36361,
 'put': 37683,
 'song': 43500,
 'thrones': 46705,
 'soundtrack': 43611,
 'playlist': 36381,
 'yoga': 52775,
 'class': 10686,
 'teaching': 45757,
 'protecting': 37391,
 'brand': 8212,
 'trade': 47415,
 'mark': 29686,
 'red': 39007,
 'bull': 8743,
 'etrhxeyiem': 16426,
 'top': 47230,
 '10': 190,
 'search': 41692,
 'engine': 16031,
 'referrals': 39101,
 'tve': 48009,
 'mike': 30770,
 'molly': 31322,
 'related': 39239,
 'thanks': 46143,
 'melissa': 30376,
 'mccarthy': 30108,
 'win': 51333,
 'emmys': 15918,
 'ok': 34154,
 'check': 10150,
 'tennis': 45969,
 'isner': 24001,
 'federer': 17355,
 'heading': 21257,
 'tiebreak': 46777,
 'watched': 50644,
 'joyful': 25426,
 '30th': 1106,
 'keeps': 26121,
 'getting': 19392,
 'better': 7159,
 'actor': 3592,
 'artists': 5445,
 'kekepalmer': 26144,
 'mecrazymatt': 30265,
 'fa': 16931,
 'cup': 12341,
 'sf': 42044,
 'carling': 9458,
 'final': 17618,
 'lost': 28666,
 'pens': 35722,
 'true': 47702,
 'leader': 27612,
 'took': 47213,
 'places': 36308,
 'ain': 4054,
 'u2019t': 48431,
 'starrhaus': 44183,
 'beachpeanuts': 6733,
 'washingtonpost': 50624,
 'bad': 6207,
 'admin': 3705,
 'yesterday': 52634,
 'qgflpxrewz': 37919,
 'hatepash1': 21107,
 'daario': 12589,
 'charming': 10091,
 'original': 34585,
 '4zpoq6zdfa': 1662,
 'foxandfriends': 18288,
 'hillary': 21676,
 'sorry': 43573,
 'facing': 16969,
 'criminal': 12057,
 'charges': 10058,
 'found': 18265,
 'email': 15848,
 'sport': 43876,
 'ct200h': 12239,
 'lexus': 27912,
 'eats': 15313,
 'asphalt': 5561,
 'sips': 42755,
 'fuel': 18653,
 'wngt4byhoj': 51531,
 'holger': 21895,
 'another': 4935,
 'selection': 41811,
 'headache': 21247,
 'carl': 9449,
 'valeri': 49473,
 'possible': 36768,
 'injury': 23469,
 '30': 1083,
 'mins': 30937,
 'cesena': 9895,
 'indy': 23369,
 'alt': 4451,
 'rightists': 39926,
 'hate': 21101,
 'guys': 20548,
 'perfect': 35761,
 'jeeze': 24735,
 '13ymtftatt': 314,
 'boys': 8129,
 'care': 9426,
 'business': 8862,
 '17': 382,
 'damn': 12692,
 'viqueens': 49961,
 'felix': 17394,
 'dez': 13703,
 'went': 50933,
 'ham': 20841,
 'topless': 47239,
 'protestors': 37407,
 'march': 29599,
 'venice': 49676,
 'beach': 6726,
 'kick': 26405,
 'gender': 19245,
 'inequality': 23377,
 'lzupp4zb2u': 29097,
 'lobodude03': 28464,
 'lair': 27266,
 'tailgate': 45447,
 'msmarbella': 31777,
 'statistar30': 44232,
 'need': 32585,
 'voter': 50177,
 'suppression': 44980,
 'documentation': 14388,
 'zrk8fqxgxe': 53431,
 '3fab5all': 1239,
 'hiberlinberlin': 21603,
 'tomgrantpi': 47140,
 'knew': 26688,
 'april': 5192,
 '1994': 480,
 'kurt': 26985,
 'cobain': 10955,
 'die': 13829,
 'must': 31982,
 'known': 26731,
 'emotional': 15929,
 'reasons': 38885,
 'emmettrensin': 15914,
 'sure': 44998,
 'liberals': 27992,
 'exploited': 16744,
 'assail': 5573,
 'whole': 51164,
 'obscures': 33865,
 'much': 31839,
 'judgejeanine': 25553,
 'realdonaldtrump': 38820,
 'mike_pence': 30773,
 'speakerryan': 43714,
 'isis': 23975,
 'films': 17610,
 'men': 30420,
 'laughing': 27458,
 'woman': 51577,
 'raped': 38589,
 'background': 6186,
 'ascuidnxyd': 5480,
 'ryan': 40806,
 'reynolds': 39734,
 'action': 3578,
 'role': 40293,
 'green': 20200,
 'lantern': 27359,
 'shows': 42505,
 'safe': 41001,
 'house': 22160,
 'isnt': 24002,
 'used': 49232,
 'barely': 6425,
 'watching': 50648,
 'dexter': 13701,
 'evening': 16510,
 'love': 28718,
 'show': 42487,
 'twaimz': 48030,
 'vines': 49930,
 'dropping': 14848,
 'ass': 5570,
 'ahs': 4015,
 'freakshow': 18404,
 'im': 23061,
 'content': 11542,
 'white': 51119,
 'boy': 8115,
 'nicki': 32913,
 'minaj': 30879,
 'best': 7103,
 'female': 17406,
 'rapper': 38600,
 'beg': 6875,
 'differ': 13844,
 'since': 42710,
 'schizophrenics': 41447,
 'recognized': 38962,
 'tomfgoodwin': 47137,
 'morganhousel': 31472,
 'id': 22760,
 'print': 37161,
 'registration': 39165,
 'concert': 11341,
 'promoters': 37325,
 'c3': 9048,
 'presents': 37049,
 'sold': 43424,
 'last': 27404,
 'truly': 47719,
 'austin': 5834,
 'city': 10587,
 'limits': 28139,
 'i2qgi0mnij': 22565,
 'trillllaa_': 47619,
 'mobile': 31230,
 'switch': 45212,
 'cmbsweden': 10874,
 'responsibility': 39576,
 'key': 26298,
 'michael': 30641,
 'moore': 31440,
 've': 49623,
 'jamesron1980': 24490,
 'wish': 51417,
 'putin': 37688,
 'hague': 20745,
 'russians': 40740,
 'deserve': 13565,
 'ukropo4ka': 48686,
 'geenpeil': 19223,
 'stacejarman': 44087,
 'brendanabc2': 8312,
 'toysrus': 47356,
 'yikes': 52685,
 'idea': 22768,
 'kids': 26432,
 'right': 39919,
 'age': 3932,
 'range': 38564,
 'hatchimals': 21098,
 'embracing': 15871,
 'oversized': 34855,
 'sun': 44862,
 'glass': 19633,
 'glasses': 19634,
 'awesome': 5979,
 'feel': 17373,
 'jackie': 24369,
 'struggle': 44640,
 'grind': 20291,
 'came': 9243,
 'heavy': 21342,
 'high': 21632,
 'god': 19786,
 'bachelor': 6171,
 'degree': 13290,
 'mine': 30893,
 'okay': 34159,
 'fidel': 17545,
 'santos': 41216,
 'maduro': 29267,
 'rt': 40572,
 'foodprincess': 18102,
 'wonderful': 51591,
 'company': 11244,
 'gr8': 20064,
 'food': 18098,
 'chinatown': 10329,
 'tour': 47319,
 'guide': 20466,
 'ziggysmogdust': 53286,
 'jaypfrancis': 24624,
 'irene': 23891,
 'shaker': 42115,
 'post': 36771,
 'pone': 36653,
 'halloween': 20824,
 'tf': 46075,
 'wensday': 50932,
 'candy': 9311,
 'sunday': 44869,
 'gon': 19869,
 'movie': 31627,
 'marathon': 29586,
 'friend': 18498,
 'twilight': 48075,
 'moon': 31430,
 'eclipse': 15378,
 'bd1': 6689,
 'runaways': 40681,
 'adventureland': 3764,
 'russian_starr': 40738,
 'listen': 28238,
 'npr': 33462,
 'interview': 23703,
 'saakashvili': 40934,
 'thoughts': 46669,
 'analysis': 4707,
 'rdf6uvjwbo': 38758,
 't_yeon9': 45387,
 'eonni': 16138,
 'mama': 29454,
 'award': 5966,
 'ost': 34647,
 'fighting': 17572,
 'jan': 24516,
 '19': 413,
 'ordinary': 34547,
 'fan': 17085,
 'somewhere': 43490,
 'papaesoco': 35230,
 'catlover1943': 9642,
 'alternet': 4461,
 'coal': 10942,
 'mining': 30910,
 'peabody': 35602,
 'etc': 16393,
 'invent': 23749,
 'robots': 40199,
 'hire': 21719,
 'workers': 51660,
 'frankthorp': 18381,
 'repkevincramer': 39413,
 'tribe': 47593,
 'legal': 27717,
 'standing': 44142,
 'treaty': 47551,
 '1851': 401,
 'army': 5352,
 'corps': 11718,
 'working': 51665,
 'fossil': 18251,
 'fuels': 18656,
 'pack': 35063,
 'brown': 8537,
 'rebound': 38909,
 'lorenzo': 28646,
 'wolfpack': 51570,
 'hoping': 22065,
 'fwleb5f3': 18793,
 'raleighnews': 38503,
 'cameron': 9250,
 'telegraph': 45909,
 'refugeecrisis': 39127,
 'supports': 44972,
 'tory': 47277,
 'drowned': 14856,
 'children': 10307,
 'beaches': 6731,
 'live': 28288,
 'radio': 38397,
 '00': 0,
 'est': 16352,
 'tune': 47922,
 'bbeilrlhw5': 6632,
 'thatfridayfeeling': 46173,
 'thought': 46667,
 'queue': 38162,
 'digi': 13862,
 'making': 29396,
 'upset': 49131,
 'caught': 9657,
 'ufo': 48593,
 'engaging': 16029,
 'warp': 50601,
 'photo': 36023,
 'asy4doye': 5652,
 'psychosix': 37521,
 'smoker': 43186,
 'beohner': 7044,
 '98': 2909,
 'fact': 16971,
 'dow': 14620,
 '634': 1996,
 'boehner': 7850,
 'owns': 34915,
 'point': 36552,
 'p2': 34973,
 'fok': 18067,
 'maddow': 29232,
 'teaparty': 45807,
 '_four_horsemen': 3132,
 'independent': 23298,
 'death': 13107,
 'penalty': 35696,
 'imaginary': 23075,
 'crimes': 12056,
 'simply': 42694,
 'barbaric': 6401,
 'mrssole': 31729,
 'lol': 28524,
 'oh': 34080,
 'free': 18419,
 'invite': 23778,
 'women': 51580,
 'church': 10497,
 'weekend': 50845,
 'miss': 30998,
 'largest': 27375,
 'book': 7950,
 'happening': 20944,
 'capitol': 9383,
 'onedirection': 34308,
 'directioner': 13959,
 'uzxs7pxykl': 49393,
 'turns': 47975,
 'match': 29898,
 'lane': 27340,
 'ramires': 38530,
 '100th': 198,
 'club': 10847,
 'that': 46165,
 'big': 7281,
 'milestone': 30827,
 'guest': 20460,
 'super': 44912,
 'kris': 26855,
 'gordon': 19963,
 'rocked': 40221,
 'wisconsin': 51406,
 'athletic': 5676,
 'armqovhe': 5349,
 'maarvi': 29171,
 'zac': 53121,
 'efron': 15562,
 'vs': 50244,
 'ashley': 5502,
 'tisdale': 46911,
 'suite': 44820,
 'life': 28039,
 'moment': 31331,
 'minus': 30941,
 'kiss': 26567,
 'powerpoint': 36840,
 'vegetarianism': 49644,
 'unhealthy': 48894,
 'double': 14584,
 'shot': 42459,
 'ticket': 46765,
 'power': 36830,
 '106': 215,
 'hear': 21289,
 'chris': 10395,
 'songs': 43504,
 'to': 47034,
 'caller': 9201,
 '888': 2705,
 '1067': 216,
 'wtf': 51859,
 'act': 3571,
 '2wayqall': 1048,
 'liespeoplealwaystell': 28036,
 'pole': 36584,
 'national': 32398,
 'margarita': 29625,
 'ash': 5489,
 'mdhibbert': 30216,
 'volvo': 50152,
 'hib': 21602,
 'plate': 36350,
 'spotted': 43903,
 'm20': 29109,
 'seriously': 41960,
 'taks': 45480,
 'steroids': 44337,
 '___': 3086,
 'eagles': 15244,
 'metal': 30525,
 'monday': 31349,
 'urban': 49166,
 'outfitters': 34750,
 'college': 11068,
 'til': 46806,
 'doesnt': 14403,
 'matter': 29953,
 'old': 34186,
 'someone': 43476,
 'brings': 8416,
 'ages': 3944,
 'ago': 3961,
 'honestly': 21991,
 '2016': 718,
 'blackfriday': 7520,
 'thewalkingdead': 46537,
 'mrrobot': 31721,
 'puksfep1ee': 37578,
 'lillian': 28116,
 'bassman': 6521,
 'images': 23074,
 'pair': 35123,
 'jason': 24565,
 'wu': 51876,
 'spring': 43919,
 '2013': 714,
 'runway': 40700,
 'trxhw2sm': 47813,
 'photography': 36030,
 'art': 5424,
 'design': 13573,
 'fashion': 17176,
 'joedoubleyou': 25177,
 'ejdionne': 15656,
 'normornstein': 33303,
 'mean': 30240,
 'already': 4437,
 'anti': 4969,
 'riots': 39975,
 'pattern': 35455,
 'sorosite': 43568,
 'color': 11094,
 'revs': 39717,
 'microsoft': 30700,
 'joins': 25285,
 'linux': 28194,
 'foundation': 18267,
 'welcomes': 50901,
 'google': 19917,
 'net': 32687,
 'community': 11233,
 'zybrg0z62r': 53511,
 'windowsphone': 51345,
 'feedly': 17367,
 'washington': 50622,
 'incoming': 23271,
 'administration': 3707,
 'president': 37055,
 'elect': 15702,
 'vidfgprill': 49871,
 '805594402798243840': 2566,
 'neutral': 32716,
 '420magazine': 1398,
 'il': 23011,
 'east': 15289,
 'peoria': 35738,
 'dispensary': 14104,
 'host': 22117,
 'ahead': 3992,
 'licen': 28014,
 'read': 38781,
 'blog': 7667,
 '10fy4n6cfx': 228,
 '805595134649892864': 2567,
 'end': 15985,
 'prohibition': 37296,
 'planning': 36337,
 'commission': 11200,
 'recommends': 38970,
 ...}

In [139]:
#model after stopwords:
#max_iter = 1000 suggestion by claude
lr = LogisticRegression(max_iter=1000)
lr.fit(train_x_counts, train_y)

acc = accuracy_score(test_y, lr.predict(test_x_counts))
print(round(acc, 4))

0.6513

Enhanced system: stop words and stemmer

In [140]:
#help from: https://www.geeksforgeeks.org/machine-learning/introduction-to-stemming/$0
from nltk.stem import PorterStemmer
porter_stemmer = PorterStemmer()

stemmed_train = []

for text in filtered_train:
    words = text.split()
    stemmed_words = [porter_stemmer.stem(word) for word in words]
    stemmed_train.append(" ".join(stemmed_words))

stemmed_test = []

for text in filtered_test:
    words = text.split()
    stemmed_words = [porter_stemmer.stem(word) for word in words]
    stemmed_test.append(" ".join(stemmed_words))

In [141]:
print(train_x.iloc[0].split())
print(stemmed_train[0].split())

['Billy', 'Crystal', 'attends', 'the', 'special', '25th', 'Anniversary', 'Screening', 'of', '\\u2019The', 'Princess', 'Bride\\u2019', 'at', 'the', 'New', 'York', 'Festival', 'http://t.co/5juFdoBK']
['billi', 'crystal', 'attend', 'special', '25th', 'anniversari', 'screen', '\\u2019th', 'princess', 'bride\\u2019', 'new', 'york', 'festiv', 'http', ':', '//t.co/5jufdobk']

In [142]:
print(train_x.iloc[30].split())
print(stemmed_train[30].split())

['It', 'would', 'be', 'poetic', 'if', 'Nintendo', 'became', 'a', 'Sony', '2nd', 'Party', 'Developer.', 'It', 'would', 'also', 'make', 'choosing', 'consoles', 'every', 'generation', 'very', 'easy']
['would', 'poetic', 'nintendo', 'becam', 'soni', '2nd', 'parti', 'develop', '.', 'would', 'also', 'make', 'choos', 'consol', 'everi', 'gener', 'easi']

In [143]:
train_x_counts = count_vect.fit_transform(stemmed_train)
test_x_counts = count_vect.transform(stemmed_test)

In [144]:
#model after stopwords and stemmer:
#max_iter = 1000 suggestion by claude
lr = LogisticRegression(max_iter=1000)
lr.fit(train_x_counts, train_y)

acc = accuracy_score(test_y, lr.predict(test_x_counts))
print(round(acc, 4))

0.65

Trying with the test:

In [145]:
train_x_counts = count_vect.fit_transform(stemmed_train)
test_x_counts = count_vect.transform(stemmed_test)

lr = LogisticRegression(max_iter=1000)
lr.fit(train_x_counts, train_y)

acc = accuracy_score(test_y, lr.predict(test_x_counts))
print(round(acc, 4))

0.65

Enhanced System: stemmer

In [146]:
stemmed_train = []

for text in train_x:
    words = text.split()
    stemmed_words = [porter_stemmer.stem(word) for word in words]
    stemmed_train.append(" ".join(stemmed_words))

stemmed_test = []

for text in test_x:
    words = text.split()
    stemmed_words = [porter_stemmer.stem(word) for word in words]
    stemmed_test.append(" ".join(stemmed_words))

In [147]:
print(train_x.iloc[0].split())
print(stemmed_train[0].split())

['Billy', 'Crystal', 'attends', 'the', 'special', '25th', 'Anniversary', 'Screening', 'of', '\\u2019The', 'Princess', 'Bride\\u2019', 'at', 'the', 'New', 'York', 'Festival', 'http://t.co/5juFdoBK']
['billi', 'crystal', 'attend', 'the', 'special', '25th', 'anniversari', 'screen', 'of', '\\u2019th', 'princess', 'bride\\u2019', 'at', 'the', 'new', 'york', 'festiv', 'http://t.co/5jufdobk']

In [148]:
train_x_counts = count_vect.fit_transform(stemmed_train)
test_x_counts = count_vect.transform(stemmed_test)

In [149]:
#max_iter = 1000 suggestion by claude
lr = LogisticRegression(max_iter=1000)
lr.fit(train_x_counts, train_y)

acc = accuracy_score(test_y, lr.predict(test_x_counts))
print(round(acc, 4))

0.6578

Embeddings: spacy. Help from:
https://deepnote.com/blog/ultimate-guide-to-the-spacy-library-in-python$0

In [150]:
!python -m spacy download en_core_web_md

Collecting en-core-web-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl (33.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 15.0 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [7]:
import spacy
nlp = spacy.load("en_core_web_md")

In [9]:
#code from claude
train_vectors = [doc.vector for doc in nlp.pipe(train_x, disable=["ner", "parser"])]
test_vectors = [doc.vector for doc in nlp.pipe(test_x, disable=["ner", "parser"])]

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
#max_iter = 1000 suggestion by claude
lr = LogisticRegression(max_iter=1000)

lr.fit(train_vectors, train_y)

acc = accuracy_score(test_y, lr.predict(test_vectors))
print(round(acc, 4))

0.5828